language: node_js
node_js:
  - "12"
before_script:
    - npm install -g webpack
script:
    - npm run docs
    - bash ./deploy-docs.sh
env:
  global:
  - ENCRYPTION_LABEL: "984893b9c2cf"
  - COMMIT_AUTHOR_EMAIL: "travis@freshheads.com"
